---
- include_tasks: ../base/general/setup_mount_permissions.yml

- name: Place per instance disk formater
  template:
    src: "format-drives.j2"
    dest: "/var/lib/cloud/scripts/per-instance/00-format-drives"
    mode: 755
  vars:
    systemd_os: ansible_service_mgr == 'systemd'
    image_user: elastic
