---
- name: Add docker repository key
  apt_key:
    url: "{{ docker_version_map[docker_version]['keys']['server'] }}"
    id: "{{ docker_version_map[docker_version]['keys']['id'] }}"

- name: Add docker repository
  apt_repository:
    repo: "{{ docker_version_map[docker_version]['repo'] }}"
    state: present

- name: Update APT package index
  apt:
    update_cache: yes

- name: Display available Docker versions
  shell: apt-cache madison docker-ce docker-ce-cli
  register: docker_versions

- name: Print available Docker versions
  debug:
    msg: "{{ docker_versions.stdout }}"
    
- name: Install docker
  apt:
    name: "{{ docker_version_map[docker_version]['package'] }}"
    state: present

- name: Pin docker-engine packet
  shell: echo "docker-engine hold" | sudo dpkg --set-selections
